### ISSUE TITLE
Freezes at "Starting at3tool..."

### ISSUE THREAD

**Issue by SammysHP** [MiniDisc-wiki/atrac-api#4]
I've tried using this with a psp_at3tool.exe that I found in this repository: https://github.com/XyLe-GBP/ATRACTool-Reloaded (I hope it is OK to share the link here.) With this version the service stops with

```
...
Starting at3tool...
```

Is it just the wrong version of the tool? Maybe you could improve the README by providing a checksum for the correct version or add more info if possible. You can also contact me directly if you don't want to share this information publicly (see contact info on my website linked in my profile).

**Comment by SammysHP** [comment]
Just one more information: I tried running `/usr/bin/wine psp_at3tool.exe -e -br 66` inside the container with the uploaded and wav converted file by hand and it worked without problems.

So I guess it's something with the script. psp_at3tool.exe and wineboot.exe become zombie processes when using the web API script, something wrong with the subprocess call?

**edit:** Indeed, the logger is not working together with `subprocess.run()` and does not consume the `PIPE`d data, so it blocks indefinitely.

**Comment by dferramosi** [comment]
same here - any luck?

**Comment by SammysHP** [comment]
@dferramosi
Yes, I had removed the PIPE output and dropped the logging of the at3tool output and I'm using the image since October without problems. But I haven't looked at the cause any deeper.

**Comment by dferramosi** [comment]
that got it working, thanks!

**Comment by thinkbrown** [comment]
I corrected the zombie wineserver issue on Oct 14th with commit https://github.com/MiniDisc-wiki/atrac-api/commit/ca2b08f521eb2a5d3a819a16f33bc7ff4f03b41a and asivery fixed some issues with Unicode handling in the logger with commit https://github.com/MiniDisc-wiki/atrac-api/commit/90acf661029928a10b3bc4db77663045d8800274. 

Can you confirm what commit you're running?

**Comment by SammysHP** [comment]
@thinkbrown I'm using 7493958 (bad) with this fix:

```diff
--- a/utils.py
+++ b/utils.py
@@ -28,6 +28,5 @@ def do_encode(input, type, logger):
   output = Path(gettempdir(), str(uuid4())).absolute()
   encoder = subprocess.run(['/usr/bin/wine', 'psp_at3tool.exe', '-e', '-br', str(bitrates[type]), 
     input, 
-    output], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
-  logger.info(encoder.stdout.decode())
-  return output
\ No newline at end of file
+    output], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
+  return output
```

**Comment by thinkbrown** [comment]
I'd try pulling and seeing if the fix asivery implemented sorts it out for you. If it doesn't I can take a look next week

**Comment by SammysHP** [comment]
Tested master (01aff8f1426403dcc1224d76ece9fc1d55c46df7) and it still doesn't work.

**Comment by thinkbrown** [comment]
Very strange. Can I get some more information on your environment (distro, docker version, etc)?

**Comment by SammysHP** [comment]
Up-to-date Arch Linux
Docker version 20.10.22, build 3a2c30b63a
python:slim         b05ccb7cc132
atrac-api 01aff8f1426403dcc1224d76ece9fc1d55c46df7
sha256 823199113c59ffcd3fc3e1855dbb88a9cd44d29e82e7a7cfc42e8c92f2a61341  psp_at3tool.ex
Testing with swagger from the browser: http://localhost:5000/

**Comment by dferramosi** [comment]
Sorry I'm just seeing these - I'll try when I get home and post env info

**Comment by thinkbrown** [comment]
Resolved in https://github.com/MiniDisc-wiki/atrac-api/commit/51563d12bff897b907a770ce6abea2a9e3f000e6 by deciding that we don't care about that data in the logs
